server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true # 무슨일이 있어도 인코딩을 utf-8로 하겠다.

spring:
  datasource:
    url : jdbc:h2:tcp://localhost/~/jwt
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]' : 100
      '[hibernate.format_sql]' : true
    show-sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    '[shop.guCoding.shopping]' : DEBUG
    '[org.hibernate.type]' : TRACE
